@startuml secrethitler personal
actor user
user -> RoleManager: requestRole(room:int, myLoc:int)
activate RoleManager
user <-- RoleManager : count down 10 sec
return role (0:hitler,1:liberal,2:pascist)

user -> RoleManager: showRole()
activate RoleManager
return role is visible

user -> RoleManager: hiddenRole()
activate RoleManager
return role is hidden

user -> PolicyManager : policyPhaseStart()
activate PolicyManager

alt fascist policies are enacted more than 3 times
user <-- PolicyManager : check whether the chancellor is hitler
end

alt # of remaining cards <= 3
PolicyManager->PolicyManager : shuffle remaining cards
end

user <-- PolicyManager : show # of remaining cards
user <-- PolicyManager : give three cards
user -> PolicyManager : selectCardDiscarded(idx:int)
user <-- PolicyManager : hide the selected card
alt veto power is opened and used
user -> PolicyManager: requestVeto() 
else veto power is not used
user -> PolicyManager : selectCardEnacted(idx:int)
alt 5 fascist policies are enacted
user <-- PolicyManager : veto power is opened
end
user <-- PolicyManager : hide the non-selected card
user -> PolicyManager : policyPhaseDone()
end
return remove all cards
@enduml
