@startuml secrethitler personal
actor user
user -> RoleManager: requestRole(room:int, myLoc:int)
activate RoleManager
user <-- RoleManager : count down 10 sec
return role (0:hitler,1:liberal,2:pascist)

user -> RoleManager: showRole()
activate RoleManager
return role is visible

user -> RoleManager: hiddenRole()
activate RoleManager
return role is hidden

user -> PolicyManager : policyPhaseStart()
activate PolicyManager
alt # of remaining cards <= 3
PolicyManager->PolicyManager : shuffle remaining cards
end
user <-- PolicyManager : show # of remaining cards
user <-- PolicyManager : give three cards
user -> PolicyManager : selectCardDiscarded(idx:int)
user <-- PolicyManager : hide the selected card
user -> PolicyManager : selectCardElected(idx:int)
user <-- PolicyManager : hide the non-selected card
user -> PolicyManager : policyPhaseDone()
return remove all cards
@enduml
